version: '3.8'

services:
  # SSO Authentication Service
  sso-auth:
    build: 
      context: ./services/sso-auth
      dockerfile: Dockerfile
    volumes:
      - ./config/sso-auth:/app/config
      - ./logs/sso-auth:/app/logs
    environment:
      - POSTGRES_DB=${QWC_DB_NAME}
      - POSTGRES_USER=${QWC_DB_USER}
      - POSTGRES_PASSWORD=${QWC_DB_PASSWORD}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
    depends_on:
      - qwc-database
    restart: unless-stopped

  # Nginx with Enhanced SSO Integration
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./shared:/var/www/shared
    depends_on:
      - sso-auth
      - qgis-desktop
      - novnc
      - file-browser
    restart: unless-stopped

  # QGIS Desktop with SSO Integration
  qgis-desktop:
    build: 
      context: ./services/qgis-desktop
      dockerfile: Dockerfile
    volumes:
      - ./shared:/home/qgis/shared
    environment:
      - SSO_AUTH_URL=http://sso-auth:5000
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    depends_on:
      - sso-auth
    restart: unless-stopped

  # File Browser with SSO
  file-browser:
    image: filebrowser/filebrowser
    volumes:
      - ./shared:/srv
      - ./config/filebrowser:/config
      - ./config/filebrowser/filebrowser.db:/database.db
    environment:
      - SSO_AUTH_URL=http://sso-auth:5000
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    depends_on:
      - sso-auth
    restart: unless-stopped

  # Database for Authentication and Services
  qwc-database:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config/postgres/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql
    environment:
      - POSTGRES_DB=${QWC_DB_NAME}
      - POSTGRES_USER=${QWC_DB_USER}
      - POSTGRES_PASSWORD=${QWC_DB_PASSWORD}
    restart: unless-stopped

networks:
  default:
    driver: bridge
