version: '3.8'

services:
  sso-auth:
    build: 
      context: ./services/sso-auth
    ports:
      - "5000:5000"
    environment:
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - QWC_DB_NAME=${QWC_DB_NAME}
      - QWC_DB_USER=${QWC_DB_USER}
      - QWC_DB_PASSWORD=${QWC_DB_PASSWORD}
    volumes:
      - ./config/sso-auth:/app/config
      - ./logs/sso-auth:/app/logs
    depends_on:
      - database

  qgis-desktop:
    build: 
      context: ./services/qgis-desktop
    volumes:
      - ./shared/qgis:/home/qgis/shared
      - ./config/qgis-desktop:/config
    environment:
      - SSO_AUTH_URL=http://sso-auth:5000
      - XPRA_PASSWORD=${XPRA_PASSWORD}
      - DISPLAY=:100
    ports:
      - "14500:14500"
    depends_on:
      - sso-auth

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - sso-auth
      - qgis-desktop

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=${QWC_DB_NAME}
      - POSTGRES_USER=${QWC_DB_USER}
      - POSTGRES_PASSWORD=${QWC_DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config/postgres/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge